import { messages } from '@/i18n'

export const t = messages({
  tr: {
    title: 'Servisler',
    subtitle: 'systemd servislerinin durumu ve yönetimi',
    refresh: 'Yenile',
    featured: 'Öne Çıkan Servisler',
    featured_empty: 'Öne çıkan servis seçilmemiş',
    featured_empty_hint: 'Ayarlar sayfasından öne çıkan servisleri belirleyebilirsiniz.',
    all: 'Tüm Servisler',
    count: '{n} servis',
    search: 'Servis ara',
    search_placeholder: 'Ad veya açıklama ile ara…',
    filter: 'Durum filtresi',
    f_all: 'Tümü',
    f_running: 'Çalışıyor',
    f_stopped: 'Durduruldu',
    f_failed: 'Hata',
    f_disabled: 'Devre Dışı',
    none_title: 'Eşleşen servis yok',
    none_hint: 'Arama metnini veya durum filtresini değiştirin.',
    empty_title: 'Servis bulunamadı',
    empty_hint: 'systemd bu sunucuda hiçbir servis bildirmedi.',
    more: 'Daha fazla göster ({n} kaldı)',

    col_service: 'Servis',
    col_state: 'Durum',
    col_boot: 'Açılışta',
    col_memory: 'Bellek',
    col_uptime: 'Çalışma süresi',
    col_actions: 'İşlemler',

    s_running: 'Çalışıyor',
    s_active: 'Aktif',
    s_stopped: 'Durduruldu',
    s_failed: 'Hata',
    s_disabled: 'Devre Dışı',
    s_activating: 'Başlatılıyor',
    s_deactivating: 'Durduruluyor',
    s_masked: 'Maskeli',
    s_not_installed: 'Kurulu değil',

    b_enabled: 'Etkin',
    b_disabled: 'Devre dışı',
    b_static: 'Statik',
    b_masked: 'Maskeli',
    b_indirect: 'Dolaylı',
    b_generated: 'Üretilmiş',
    b_runtime: 'Geçici etkin',
    b_transient: 'Geçici',
    b_unknown: '—',

    critical: 'Kritik',
    protected: 'Korumalı',
    socket: 'Soket ile başlatılır: {names}',
    pid: 'PID {pid}',

    v_start: 'Başlat',
    v_stop: 'Durdur',
    v_restart: 'Yeniden Başlat',
    v_reload: 'Yapılandırmayı Yeniden Yükle',
    v_enable: 'Etkinleştir',
    v_disable: 'Devre Dışı Bırak',
    logs: 'Loglar',
    action_for: '{action}: {name}',
    protected_hint: 'Korumalı çekirdek servis: bu işlem panelden yapılamaz',

    done_start: '{name} başlatıldı.',
    done_stop: '{name} durduruldu.',
    done_restart: '{name} yeniden başlatıldı.',
    done_reload: '{name} yapılandırması yeniden yüklendi.',
    done_enable: '{name} açılışta başlayacak şekilde etkinleştirildi.',
    done_disable: '{name} açılışta başlamayacak şekilde devre dışı bırakıldı.',
    panel_restarting: 'Panel yeniden başlatılıyor. Birkaç saniye sonra sayfayı yenileyin.',
    panel_stopped: 'Panel durduruldu. Yeniden açmak için sunucuda "systemctl start myserver" komutunu çalıştırın.',

    c_title_stop: 'Servisi durdur',
    c_title_restart: 'Servisi yeniden başlat',
    c_title_disable: 'Servisi devre dışı bırak',
    c_msg_stop: '{name} ({unit}) servisi durdurulacak. Bu servise bağlı işlevler çalışmayı bırakır.',
    c_msg_restart: '{name} ({unit}) servisi yeniden başlatılacak. Servis kısa süreliğine kesintiye uğrar.',
    c_msg_disable: '{name} ({unit}) servisi sunucu açılışında artık otomatik başlamayacak. Çalışan servis durdurulmaz.',
    cancel: 'Vazgeç',

    w_ssh:
      'DİKKAT: SSH servisini durdurmak, devre dışı bırakmak veya yeniden başlatmak sunucuya uzaktan erişiminizi kesebilir. Sunucuya fiziksel (klavye/ekran) erişiminiz yoksa bu panel oturumu sunucuya ulaşmanın tek yolu olabilir; panel de erişilemez olursa sunucuya hiçbir şekilde bağlanamazsınız. Panel SSH yapılandırmasını değiştirmez.',
    w_ssh_socket:
      'Bu sunucuda SSH bağlantıları ayrıca {names} üzerinden kabul ediliyor; servisi durdurmak açık oturumları kapatır.',
    w_panel_stop:
      'MyServer paneli durdurulursa veya devre dışı bırakılırsa bu arayüz kullanılamaz. Yeniden açmak için SSH ya da konsol erişimi gerekir.',
    w_panel_restart: 'Panel yeniden başlatılırken bu arayüz kısa bir süre kullanılamaz ve açık terminal oturumları kapanır.',
    w_network:
      'Bu servis sunucunun ağ bağlantısını veya ad çözümlemesini yönetir. İşlem sırasında sunucuya ve bu panele erişim kesilebilir.',
    w_container: 'Bu servis durduğunda çalışan tüm konteynerler ve onlara bağlı uygulamalar da durur.',
    w_core: 'Bu bir çekirdek sistem servisidir. İşlem sistemin kararlılığını bozabilir.',

    logs_title: '{name} logları',
    logs_desc: '{unit} · journald kayıtları',
    logs_lines: 'Satır sayısı',
    logs_n: 'Son {n} satır',
    logs_live: 'Canlı izle',
    logs_live_on: 'Canlı akış açık (en fazla 10 dakika)',
    logs_live_ended: 'Canlı akış sona erdi. Yeniden başlatmak için "Canlı izle" seçeneğini açın.',
    logs_connecting: 'Bağlanıyor…',
    logs_empty: 'Log kaydı yok',
    logs_empty_hint: 'journald bu servis için kayıt tutmamış.',
    logs_loading: 'Loglar okunuyor…',
    close: 'Kapat',

    widget_title: 'Servis Durumları',
    widget_all: 'Tümünü Gör',
    widget_open: '{name}: {state}. Servisler sayfasını aç',

    set_title: 'Öne Çıkan Servisler',
    set_subtitle: 'Servisler sayfasının başında ve ana sayfadaki "Servis Durumları" kartında gösterilir.',
    set_empty: 'Liste boş',
    set_empty_hint: 'Aşağıdan servis ekleyin.',
    set_add: 'Ekle',
    set_pick: 'Kurulu servislerden seç',
    set_pick_placeholder: 'Servis seçin…',
    set_manual: 'Veya birim adını yazın',
    set_manual_hint: 'Örnek: nginx.service. Kurulu olmayan servis "Kurulu değil" olarak gösterilir.',
    set_invalid: 'Servis adı geçersiz.',
    set_duplicate: 'Bu servis zaten listede.',
    set_full: 'En fazla {n} servis öne çıkarılabilir.',
    set_up: '{name}: yukarı taşı',
    set_down: '{name}: aşağı taşı',
    set_remove: '{name}: listeden çıkar',
    set_save: 'Kaydet',
    set_reset: 'Varsayılana Dön',
    set_saved: 'Öne çıkan servisler kaydedildi.',
    set_admin: 'Bu ayarı yalnızca yöneticiler değiştirebilir.',
  },
})
