import { messages } from '@/i18n'

export const t = messages({
  tr: {
    title: 'Dosyalar',
    subtitle: 'İzin verilen dizinlerdeki dosyaları yönetin',
    places: 'Konumlar',
    placesHint: 'Yönetici tarafından izin verilen dizinler',
    noRoots: 'Tanımlı dizin yok',
    noRootsHint: 'Dosya yöneticisinin erişebileceği dizinler Ayarlar bölümünden tanımlanır.',
    rootMissing: 'Sunucuda yok',
    rootFree: '{free} boş / {total}',
    rootUsage: '{name} doluluk oranı',
    breadcrumb: 'Konum',
    up: 'Üst dizin',
    refresh: 'Yenile',
    newFolder: 'Yeni Klasör',
    upload: 'Yükle',
    listView: 'Liste görünümü',
    gridView: 'Izgara görünümü',
    sortBy: 'Sıralama',
    colName: 'Ad',
    colSize: 'Boyut',
    colMode: 'İzinler',
    colOwner: 'Sahip',
    colModified: 'Değiştirilme',
    sortAsc: 'artan',
    sortDesc: 'azalan',
    sortColumn: '{column} sütununa göre sırala',
    emptyDir: 'Bu klasör boş',
    emptyDirHint: 'Dosyaları buraya sürükleyip bırakabilir veya Yükle düğmesini kullanabilirsiniz.',
    emptyDirHintReadOnly: 'Bu klasörde gösterilecek öğe yok.',
    loadingDir: 'Klasör okunuyor…',
    truncated: 'Bu klasör çok fazla öğe içeriyor; yalnızca ilk {count} öğe okundu.',
    showing: '{shown} / {total} öğe gösteriliyor',
    showMore: 'Daha Fazla Göster',
    pageCap: 'En fazla {count} öğe gösterilebilir.',
    itemCount: '{count} öğe',
    selectedCount: '{count} öğe seçildi',
    selectAll: 'Tümünü seç',
    clearSelection: 'Seçimi temizle',
    selectItem: '{name} öğesini seç',
    itemActions: '{name} için işlemler',
    actions: 'İşlemler',
    open: 'Aç',
    download: 'İndir',
    downloadZip: 'ZIP olarak indir',
    move: 'Taşı',
    copy: 'Kopyala',
    rename: 'Yeniden Adlandır',
    remove: 'Sil',
    zip: 'ZIP Oluştur',
    unzip: 'ZIP Aç',
    properties: 'Özellikler',
    edit: 'Düzenle',
    cancel: 'Vazgeç',
    close: 'Kapat',
    save: 'Kaydet',
    create: 'Oluştur',
    typeFolder: 'Klasör',
    typeFile: 'Dosya',
    typeSymlink: 'Sembolik bağlantı',
    typeOther: 'Özel dosya',
    linkUnreachable: 'Bağlantı hedefi yok veya izin verilen dizinin dışında',
    linkOutside: 'Bu bağlantının hedefi yok ya da izin verilen dizinin dışında olduğu için açılamaz.',
    otherNotOpenable: 'Bu öğe türü açılamaz.',
    dropHere: 'Yüklemek için dosyaları buraya bırakın',
    folderUploadUnsupported: 'Klasörler sürükleyerek yüklenemez; yalnızca dosyalar eklendi.',
    readOnlyNote: 'Salt okunur erişiminiz var. Değişiklik yapmak için yönetici yetkisi gerekir.',

    folderName: 'Klasör adı',
    newFolderTitle: 'Yeni Klasör',
    newFolderIn: '{path} içinde oluşturulacak',
    folderCreated: 'Klasör oluşturuldu.',
    renameTitle: 'Yeniden Adlandır',
    newName: 'Yeni ad',
    renamed: 'Ad değiştirildi.',
    nameRequired: 'Ad boş olamaz.',
    nameInvalid: "Ad '/' veya '\\' içeremez; '.' ve '..' kullanılamaz.",

    deleteTitle: 'Kalıcı Olarak Sil',
    deleteOne: '"{name}" kalıcı olarak silinecek.',
    deleteMany: 'Seçilen {count} öğe kalıcı olarak silinecek.',
    deleteCounting: 'İçerik sayılıyor…',
    deleteTotals: 'Alt klasörlerle birlikte toplam {items} öğe ({size}) silinecek.',
    deleteTotalsTruncated: 'Alt klasörlerle birlikte {items} öğeden fazlası (en az {size}) silinecek.',
    deleteCountFailed: 'İçerik sayılamadı: {message}',
    deleteWarning: 'Bu işlem geri alınamaz. Silinen dosyalar çöp kutusuna taşınmaz.',
    deleteConfirmWord: 'sil',
    deleteStarted: 'Silme işlemi başlatıldı.',

    moveTitle: 'Taşınacak Klasörü Seçin',
    copyTitle: 'Kopyalanacak Klasörü Seçin',
    extractTitle: 'Arşivin Açılacağı Klasörü Seçin',
    moveHere: 'Buraya Taşı',
    copyHere: 'Buraya Kopyala',
    extractHere: 'Buraya Aç',
    conflictLabel: 'Aynı adda öğe varsa',
    conflictRename: 'Yeni adla kaydet',
    conflictOverwrite: 'Üzerine yaz',
    conflictSkip: 'Atla',
    moveStarted: 'Taşıma işlemi başlatıldı.',
    copyStarted: 'Kopyalama işlemi başlatıldı.',
    extractStarted: 'Arşiv açma işlemi başlatıldı.',
    extractSafety: 'Arşivdeki sembolik bağlantılar ve hedef klasörün dışına çıkan adlar güvenlik nedeniyle atlanır.',

    zipTitle: 'ZIP Oluştur',
    zipName: 'Arşiv adı',
    zipIn: '{count} öğe, {path} içinde arşivlenecek',
    zipStarted: 'Arşiv oluşturma işlemi başlatıldı.',
    zipDefaultName: 'arsiv',

    picker: 'Klasör Seç',
    pickerSelect: 'Bu Klasörü Seç',
    pickerChoose: 'Bir konum seçin',
    pickerNoFolders: 'Alt klasör yok',
    pickerNoFoldersHint: 'Bu klasörü seçebilir veya yeni bir klasör oluşturabilirsiniz.',
    pickerCurrent: 'Seçilen klasör',
    pickerNone: 'Henüz seçilmedi',
    pickerEnter: '{name} klasörüne gir',

    propsTitle: 'Özellikler',
    propName: 'Ad',
    propPath: 'Konum',
    propType: 'Tür',
    propSize: 'Boyut',
    propContent: 'İçerik',
    propMode: 'İzinler',
    propOwner: 'Sahip',
    propGroup: 'Grup',
    propModified: 'Değiştirilme',
    propTarget: 'Bağlantı hedefi',
    propMime: 'İçerik türü',
    propUnknown: 'Bilinmiyor',
    sizeCalculating: 'Hesaplanıyor… ({items} öğe)',
    sizeResult: '{size} ({items} öğe)',
    sizeResultTruncated: 'En az {size} ({items} öğeden fazla)',
    sizeFailed: 'Hesaplanamadı: {message}',
    chmodLabel: 'İzinleri değiştir (sekizlik)',
    chmodHint: 'Örnek: 644 (dosya), 755 (klasör)',
    chmodApply: 'Uygula',
    chmodInvalid: 'Üç haneli sekizlik bir değer girin (örneğin 644).',
    chmodDone: 'İzinler değiştirildi.',

    previewUnavailable: 'Önizleme yüklenemedi.',
    textTitleView: 'Metin Görüntüle',
    textTitleEdit: 'Metin Düzenle',
    textContent: 'Dosya içeriği',
    textSaved: 'Dosya kaydedildi.',
    textUnsaved: 'Kaydedilmemiş değişiklikler var. Kapatılsın mı?',
    textDiscard: 'Değişiklikleri At',
    textUnsavedTitle: 'Kaydedilmemiş Değişiklikler',

    uploadsTitle: 'Yüklemeler',
    uploadQueued: 'Sırada',
    uploadDone: 'Tamamlandı',
    uploadCancelled: 'İptal edildi',
    uploadConflict: 'Aynı adda dosya var',
    uploadOverwrite: 'Üzerine Yaz',
    uploadCancel: '{name} yüklemesini iptal et',
    uploadTooLarge: 'Dosya en büyük yükleme boyutunu ({max}) aşıyor.',
    uploadClear: 'Tamamlananları Temizle',
    uploadTo: '{path} konumuna',
    uploadFinished: '{count} dosya yüklendi.',

    jobsTitle: 'Dosya İşlemleri',
    jobCopy: 'Kopyalama',
    jobMove: 'Taşıma',
    jobDelete: 'Silme',
    jobZip: 'Arşivleme',
    jobExtract: 'Arşiv açma',
    jobSize: 'Boyut hesaplama',
    jobScanning: 'İçerik taranıyor…',
    jobPreparing: 'Hazırlanıyor…',
    jobProgress: '{done} / {total} öğe',
    jobProgressBytes: '{done} / {total}',
    jobDone: 'Tamamlandı',
    jobDoneSkipped: 'Tamamlandı, {count} öğe atlandı',
    jobFailed: 'Başarısız',
    jobCancelled: 'İptal edildi',
    jobCancel: 'İşlemi iptal et',
    jobDismiss: 'Listeden kaldır',
    jobFinishedToast: '{kind} tamamlandı.',
    jobFinishedSkippedToast: '{kind} tamamlandı; {count} öğe atlandı.',
    jobFailedToast: '{kind} başarısız: {message}',
    jobCancelledToast: '{kind} iptal edildi.',

    settingsTitle: 'Dosya Yöneticisi',
    settingsSubtitle: 'Erişilebilir dizinler ve yükleme sınırları',
    rootsLabel: 'İzin verilen dizinler',
    rootsExplain:
      'Dosya yöneticisi yalnızca bu dizinlerin ve alt klasörlerinin içeriğini gösterir ve değiştirir. Diğer modüllerdeki klasör seçiciler de bu listeyle sınırlıdır.',
    rootsWarning:
      'Buraya eklenen bir dizindeki tüm dosyalar panele giriş yapan her kullanıcı tarafından okunabilir ve yöneticiler tarafından değiştirilebilir. Sistem dizinlerini (/etc, /var, /root gibi) eklemeyin; yalnızca kullanıcı verisi içeren dizinleri açın.',
    rootsEmpty: 'Hiç dizin tanımlı değil. Dosya yöneticisi hiçbir dizine erişemez.',
    rootAdd: 'Dizin Ekle',
    rootPath: 'Dizin yolu',
    rootPathPlaceholder: '/srv/veri',
    rootRemove: '{path} dizinini listeden kaldır',
    rootInvalid: "Dizin yolu '/' ile başlamalı ve '..' içermemelidir.",
    rootDuplicate: 'Bu dizin zaten listede.',
    rootLimit: 'En fazla 32 dizin tanımlanabilir.',
    maxUpload: 'En büyük yükleme boyutu (MB)',
    maxUploadHint: 'Tek bir dosya için üst sınır. Şu anki değer: {size}',
    maxExtract: 'En büyük açılmış arşiv boyutu (MB)',
    maxExtractHint: 'Bir arşivin açıldığında kaplayabileceği toplam alan. Şu anki değer: {size}',
    numberInvalid: 'Değer {min} ile {max} arasında bir tam sayı olmalıdır.',
    settingsSaved: 'Dosya yöneticisi ayarları kaydedildi.',
    settingsUnsaved: 'Kaydedilmemiş değişiklikler var.',
    settingsReset: 'Geri Al',
  },
})
