import { messages } from '@/i18n'

export const t = messages({
  tr: {
    pageTitle: 'Ağ',
    pageDescription: 'Ağ arayüzleri, DNS, ağ geçidi ve güvenlik duvarı',
    tabsLabel: 'Ağ bölümleri',
    tabNetwork: 'Ağ',
    tabFirewall: 'Güvenlik Duvarı',
    refresh: 'Yenile',
    unknown: 'Belirlenemedi',
    none: 'Yok',
    yes: 'Evet',
    no: 'Hayır',
    close: 'Kapat',
    cancel: 'Vazgeç',

    // Network tab
    summaryTitle: 'Genel Bilgiler',
    hostname: 'Sunucu adı',
    manager: 'Ağ yöneticisi',
    managerEvidence: 'Tespit gerekçesi',
    gateway: 'Ağ geçidi',
    gatewayTitle: 'Ağ Geçidi ve DNS',
    gatewayV4: 'IPv4 ağ geçidi',
    gatewayV6: 'IPv6 ağ geçidi',
    gatewayNone: 'Varsayılan rota yok',
    gatewayOnLink: 'doğrudan bağlı',
    gatewayVia: '{address} ({iface})',
    dnsServers: 'DNS sunucuları',
    dnsSearch: 'Arama alan adları',
    dnsSource: 'Kaynak',
    dnsNone: 'DNS sunucusu tanımlı değil',
    dnsResolved: 'systemd-resolved kullanılıyor',
    subnets: 'Yerel ağlar',
    subnetsNone: 'Özel (yerel) bir ağ bulunamadı',
    interfacesTitle: 'Ağ Arayüzleri',
    interfacesEmpty: 'Ağ arayüzü bulunamadı',
    interfacesEmptyDesc: 'Çekirdek hiçbir ağ arayüzü bildirmedi.',
    virtualShow: 'Sanal arayüzleri göster ({count})',
    virtualHide: 'Sanal arayüzleri gizle ({count})',
    virtualHint: 'Docker köprüleri, veth çiftleri, tüneller ve loopback',
    kindEthernet: 'Ethernet',
    kindWifi: 'Kablosuz',
    kindBridge: 'Köprü',
    kindBond: 'Bond',
    kindVlan: 'VLAN',
    kindVirtual: 'Sanal',
    kindLoopback: 'Loopback',
    stateUp: 'Bağlı',
    stateDown: 'Bağlı değil',
    stateDormant: 'Beklemede',
    stateLower: 'Alt katman kapalı',
    stateDisabled: 'Devre dışı',
    stateUnknown: 'Bilinmiyor',
    defaultRoute: 'Varsayılan rota',
    ipv4: 'IPv4',
    ipv6: 'IPv6',
    noAddress: 'Adres yok',
    scopeGlobal: 'genel',
    scopeUla: 'yerel (ULA)',
    scopeLink: 'bağlantı',
    scopeHost: 'sunucu',
    mac: 'MAC',
    mtu: 'MTU',
    speed: 'Bağlantı hızı',
    speedValue: '{speed} Mb/s',
    speedUnknown: 'Bildirilmiyor',
    duplexFull: 'tam çift yönlü',
    duplexHalf: 'yarı çift yönlü',
    carrier: 'Taşıyıcı',
    carrierYes: 'Var',
    carrierNo: 'Yok',
    linkUptime: 'Bağlantı süresi',
    linkUptimeUnknown: 'Belirlenemiyor',
    driver: 'Sürücü',
    master: 'Bağlı olduğu arayüz',
    rx: 'Alınan',
    tx: 'Gönderilen',
    packets: '{count} paket',
    errors: 'Hata',
    dropped: 'Düşen',
    errorsValue: 'alınan {rx} / gönderilen {tx}',
    statsUnavailable: 'Sayaçlar okunamıyor',
    netplanTitle: 'Netplan Yapılandırması',
    netplanSubtitle: 'Parolalar ve anahtarlar gizlenerek gösterilir',
    netplanShow: 'Yapılandırmayı Göster',
    netplanAbsent: 'Bu sunucu Netplan kullanmıyor',
    netplanAbsentDesc: '/etc/netplan dizini bulunamadı.',
    netplanEmpty: 'Netplan dosyası yok',
    netplanEmptyDesc: '/etc/netplan içinde .yaml dosyası bulunamadı.',
    netplanReadOnly: 'Bu görünüm salt okunurdur; panel ağ yapılandırmasını değiştirmez.',
    netplanRedacted: '{count} gizli değer maskelendi',
    netplanTruncated: 'Dosya çok büyük olduğu için yalnızca baş kısmı gösteriliyor.',
    netplanMeta: '{size} · izinler {mode} · {date}',
    portsTitle: 'Dinlenen Portlar',
    portsSubtitle: 'Bağlantı kabul eden servisler',
    portsEmpty: 'Dinlenen port yok',
    portsEmptyDesc: 'Hiçbir servis bağlantı beklemiyor.',
    port: 'Port',
    protocol: 'Protokol',
    bindAddress: 'Dinlenen adres',
    reach: 'Erişim',
    owner: 'Sahip',
    process: 'Süreç',
    processUnknown: 'Belirlenemiyor',
    reachAll: 'Tüm arayüzler',
    reachLoopback: 'Yalnızca sunucu içi',
    reachSpecific: 'Belirli adres',
    portsNote: 'Tüm arayüzlerde dinlenen bir porta dışarıdan erişilip erişilemeyeceğini güvenlik duvarı kuralları belirler.',

    // Firewall tab
    fwTitle: 'Güvenlik Duvarı (UFW)',
    fwActive: 'Etkin',
    fwInactive: 'Etkin değil',
    fwNotInstalled: 'Kurulu değil',
    fwNotInstalledTitle: 'UFW kurulu değil',
    fwNotInstalledDesc: 'Bu sunucuda UFW güvenlik duvarı bulunmuyor. Panel paket kurmaz; sunucuda aşağıdaki komutla kurabilirsiniz. Kurulumdan sonra bu sayfayı yenileyin.',
    fwInactiveWarn: 'Güvenlik duvarı etkin değil',
    fwInactiveWarnDesc: 'Sunucuda dinlenen tüm portlar, sunucuya ulaşabilen herkese açıktır.',
    fwInactiveRules: 'Güvenlik duvarı etkin olmadığı için aşağıdaki kurallar şu anda uygulanmıyor; etkinleştirildiğinde geçerli olacaklar.',
    fwEnable: 'Etkinleştir',
    fwDisable: 'Devre Dışı Bırak',
    fwAdminOnly: 'Güvenlik duvarını yalnızca yöneticiler değiştirebilir.',
    policies: 'Varsayılan Politikalar',
    policyIncoming: 'Gelen',
    policyOutgoing: 'Giden',
    policyRouted: 'Yönlendirilen',
    logging: 'Günlükleme',
    loggingOff: 'Kapalı',
    policyAllow: 'İzin ver',
    policyDeny: 'Engelle',
    policyReject: 'Reddet',
    policyDisabled: 'Devre dışı',
    sshPort: 'SSH portu',
    panelPort: 'Panel portu',
    panelPortLocal: '{port} (yalnızca sunucu içi, kural gerekmez)',
    rulesTitle: 'Kurallar',
    rulesEmpty: 'Kural tanımlı değil',
    rulesEmptyDesc: 'Henüz hiçbir güvenlik duvarı kuralı eklenmemiş.',
    ruleAdd: 'Kural Ekle',
    ruleNumber: 'No',
    rulePort: 'Port',
    ruleProtocol: 'Protokol',
    ruleSource: 'Kaynak',
    ruleAction: 'Eylem',
    ruleComment: 'Açıklama',
    ruleDelete: 'Kuralı sil',
    ruleAnyPort: 'Tümü',
    ruleAnyProto: 'Tümü',
    ruleAnywhere: 'Her yerden',
    ruleOut: 'giden',
    ruleRouted: 'yönlendirme',
    ruleOn: '{iface} arayüzü',
    ruleTo: 'hedef {address}',
    ruleFromPort: 'kaynak portu {port}',
    ruleProtectsSsh: 'SSH erişimi',
    ruleProtectsPanel: 'Panel erişimi',
    actionAllow: 'İzin ver',
    actionDeny: 'Engelle',
    actionReject: 'Reddet',
    actionLimit: 'Sınırla',
    actionAllowHint: 'Bağlantılara izin verilir.',
    actionDenyHint: 'Bağlantılar sessizce düşürülür.',
    actionRejectHint: 'Bağlantılar reddedilir ve karşı tarafa bildirilir.',
    actionLimitHint: 'İzin verilir; aynı adresten 30 saniyede 6 veya daha fazla bağlantı denemesi engellenir.',

    // Enable / disable dialogs
    enableTitle: 'Güvenlik duvarını etkinleştir',
    enableMessage: 'Güvenlik duvarı etkinleştirildiğinde yalnızca kurallarda izin verilen bağlantılar kabul edilir; diğer tüm gelen bağlantılar engellenir. Ayar, sunucu yeniden başlatıldığında da geçerli kalır.',
    enableMissing: 'Erişiminizin kesilmemesi için şu kurallar eklenecek:',
    enableMissingSsh: 'SSH ({port}/{protocol})',
    enableMissingPanel: 'MyServer paneli ({port}/{protocol})',
    enableSourceLabel: '{name} için izin verilecek kaynak',
    enableAnyWarn: '"Her yerden" seçilen portlar internete açılır. Sunucu internetten erişilebilir durumdaysa herkes bu porta bağlanmayı deneyebilir.',
    enableClientOutside: 'Bağlandığınız adres ({ip}) tespit edilen yerel ağların dışında. Yalnızca yerel ağa izin verirseniz bu adresten erişiminiz kesilir.',
    enableSshNote: 'Panel SSH yapılandırmasını değiştirmez; yalnızca SSH portu için güvenlik duvarı kuralı ekler.',
    enableReady: 'SSH ve panel erişimi için gerekli kurallar mevcut.',
    enableConfirm: 'Etkinleştir',
    enableConfirmAdd: 'Kuralları Ekle ve Etkinleştir',
    enabledToast: 'Güvenlik duvarı etkinleştirildi.',
    disableTitle: 'Güvenlik duvarını devre dışı bırak',
    disableMessage: 'Güvenlik duvarı kapatıldığında hiçbir kural uygulanmaz ve sunucuda dinlenen tüm portlar, sunucuya ulaşabilen herkese açılır. Kurallar silinmez.',
    disableConfirm: 'Devre Dışı Bırak',
    disabledToast: 'Güvenlik duvarı devre dışı bırakıldı.',

    // Add rule
    addTitle: 'Güvenlik duvarı kuralı ekle',
    addService: 'Hazır servis',
    addServiceCustom: 'Özel port',
    addPort: 'Port veya port aralığı',
    addPortHint: 'Tek port (445) veya aralık (5000:5010)',
    addProtocol: 'Protokol',
    protoTcp: 'TCP',
    protoUdp: 'UDP',
    protoAny: 'TCP ve UDP',
    addSource: 'Kaynak',
    sourceSubnet: '{cidr} — yerel ağ ({iface})',
    sourceBlock: '{cidr} — tüm özel ağ bloğu',
    sourceCustom: 'Belirli bir adres veya ağ…',
    sourceAny: 'Her yerden (internet)',
    addSourceCustom: 'Adres veya ağ',
    addSourceCustomHint: 'Örnek: 192.168.1.10 veya 192.168.1.0/24',
    addAction: 'Eylem',
    addComment: 'Açıklama (isteğe bağlı)',
    addCommentHint: 'En fazla 64 karakter; İngilizce harf, rakam, boşluk ve _.,:()/+- kullanılabilir.',
    addAnyWarnTitle: 'Bu servis internete açılacak',
    addAnyWarn: 'Kaynak "Her yerden" seçildiğinde bu porta internet dahil her adresten bağlanılabilir. Yalnızca gerçekten herkese açık olması gereken servisler için kullanın.',
    addLanOnlyWarn: 'Bu servis (dosya paylaşımı vb.) internete açılmak üzere tasarlanmamıştır. Yerel ağ ile sınırlamanız önerilir.',
    addNoLan: 'Sunucunun bağlı olduğu bir yerel ağ tespit edilemedi; kaynağı elle belirtin.',
    addContinue: 'Devam',
    addConfirmTitle: 'Kuralı onayla',
    addConfirmMessage: '{action}: {port}/{protocol} portuna {source} gelen bağlantılar.',
    addConfirmFromAny: 'her yerden (internet dahil)',
    addConfirmFrom: '{source} adresinden',
    addConfirmApply: 'Kural hemen uygulanır.',
    addConfirmInactive: 'Güvenlik duvarı etkin olmadığı için kural kaydedilir ve etkinleştirildiğinde uygulanır.',
    addRiskWarn: 'Bu kural SSH veya panel portunu engelliyor. Uygulandığında sunucuya ya da panele erişiminiz kesilebilir.',
    addRiskText: 'ONAYLIYORUM',
    addConfirm: 'Kuralı Ekle',
    addedToast: 'Kural eklendi.',
    errPort: 'Port 1 ile 65535 arasında bir sayı veya 5000:5010 biçiminde bir aralık olmalıdır.',
    errRangeProto: 'Port aralığı için TCP veya UDP seçilmelidir.',
    errSource: 'Kaynak geçerli bir IP adresi veya ağ olmalıdır.',
    errComment: 'Açıklama geçersiz karakter içeriyor veya çok uzun.',

    // Delete rule
    deleteTitle: 'Kuralı sil',
    deleteMessage: 'Şu kural silinecek: {rule}',
    deleteAllowEffect: 'Bu kuralın izin verdiği bağlantılar artık kabul edilmeyecek.',
    deleteBlockEffect: 'Bu kuralın engellediği bağlantılar, başka bir kural engellemiyorsa kabul edilebilir.',
    deleteProtectedWarn: 'Bu kural {what} açık tutuyor. Silerseniz sunucuya erişiminiz kesilebilir ve yeniden erişmek için sunucunun başında olmanız gerekebilir.',
    deleteProtectedSsh: 'SSH erişimini',
    deleteProtectedPanel: 'panel erişimini',
    deleteConfirm: 'Kuralı Sil',
    deleteRiskText: 'ONAYLIYORUM',
    deletedToast: 'Kural silindi.',

    // Settings sections
    setNetworkTitle: 'Ağ',
    setNetworkLink: 'Ağ sayfasını aç',
    setFirewallTitle: 'Güvenlik Duvarı',
    setFirewallLink: 'Güvenlik duvarını aç',
    setFirewallStatus: 'Durum',
    setFirewallRules: 'Kural sayısı',
    setFirewallIncoming: 'Gelen bağlantılar',
  },
})
