import { messages } from '@/i18n'

export const t = messages({
  tr: {
    pageTitle: 'Yedekleme',
    pageDescription: 'Kurulu uygulamaların ayarlarını ve verilerini yedekleyin, doğrulayın ve geri yükleyin.',
    adminOnlyTitle: 'Yönetici yetkisi gerekiyor',
    adminOnlyDesc: 'Yedekler uygulamaların gizli bilgilerini içerdiği için bu bölümü yalnızca yöneticiler kullanabilir.',
    cancel: 'Vazgeç',
    close: 'Kapat',
    save: 'Kaydet',
    yes: 'Evet',
    no: 'Hayır',

    // Explanation
    aboutTitle: 'Bir yedek neleri içerir?',
    aboutConfig: 'Uygulamanın kurulu olduğu haliyle yapılandırması: portlar, ortam değişkenleri, birim ve klasör eşlemeleri.',
    aboutVolumes: 'Uygulamanın tüm Docker veri birimlerinin içeriği (veritabanı dosyaları dahil).',
    aboutBinds: 'Uygulamaya bağlanan sunucu klasörlerinin içeriği (isteğe bağlı olarak dışarıda bırakılabilir).',
    aboutNot: 'Yedek, Docker görüntülerini içermez; geri yüklemede görüntüler gerekirse yeniden indirilir. Sistem klasörleri (örneğin Docker soketi) yedeğe alınmaz.',
    secretsTitle: 'Yedekler gizli bilgi içerir',
    secretsBody:
      'Her yedek, uygulamanın veritabanı parolaları gibi gizli değerlerini ve tüm verilerini içerir. Yedek dosyasını ele geçiren kişi bu bilgilere erişir. Dosyaları yalnızca güvendiğiniz yerlerde saklayın.',
    encOnTitle: 'Yeni yedekler şifreleniyor',
    encOnBody:
      'Yedekler {cipher} ile şifrelenir (anahtar türetme: {kdf}). Şifreli bir yedeği başka bir sunucuda açmak için parolayı bilmeniz gerekir; parolayı unutursanız yedek açılamaz.',
    encOffTitle: 'Yedekler şifrelenmiyor',
    encOffBody:
      'Şu anda alınan yedekler şifresiz olarak yazılıyor. Dosyaları sunucu dışına çıkaracaksanız Ayarlar > Yedekleme bölümünden bir şifreleme parolası belirleyin.',
    encErrorTitle: 'Şifreleme anahtarı okunamıyor',
    openSettings: 'Yedekleme ayarları',

    // Apps
    appsTitle: 'Uygulamalar',
    appsUnavailable: 'Uygulama listesi alınamadı',
    noAppsTitle: 'Kurulu uygulama yok',
    noAppsDesc: 'Yedeklenecek bir uygulama bulunmuyor. Önce Uygulamalar sayfasından bir uygulama kurun.',
    goApps: 'Uygulamalara Git',
    lastBackup: 'Son yedek',
    never: 'Henüz yedek alınmadı',
    backupCount: '{count} yedek',
    lastFailed: 'Son deneme başarısız',
    lastCancelled: 'Son deneme iptal edildi',
    scheduleOff: 'Zamanlama kapalı',
    nextRun: 'Sonraki: {time}',
    dataLocations: '{volumes} veri birimi, {binds} klasör',
    notInstalled: 'Kurulu değil',
    orphansTitle: 'Kurulu olmayan uygulamaların yedekleri',
    orphansDesc: 'Bu uygulamalar şu anda kurulu değil. Yedeği geri yüklerseniz uygulama yedekteki yapılandırmayla yeniden kurulur.',
    running: 'İşlem sürüyor',

    // Actions
    backupNow: 'Şimdi Yedekle',
    restore: 'Geri Yükle',
    download: 'İndir',
    remove: 'Sil',
    schedule: 'Zamanlama',
    verify: 'Doğrula',
    upload: 'Yedek Yükle',
    more: 'Diğer işlemler',
    downloadLast: 'Son yedeği indir',
    deleteLast: 'Son yedeği sil',

    // Backup dialog
    backupTitle: '{name} uygulamasını yedekle',
    backupStopInfo:
      'Verilerin tutarlı olması için uygulama yedekleme süresince durdurulur ve işlem bitince (başarısız olsa bile) yeniden başlatılır. Bu sürede uygulamaya erişilemez.',
    liveLabel: 'Çalışırken yedekle',
    liveHint: 'Uygulama durdurulmaz.',
    liveWarnTitle: 'Tutarsız yedek riski',
    liveWarn:
      'Uygulama çalışırken alınan yedekte veritabanı dosyaları yazılmakta oldukları bir anda kopyalanabilir. Böyle bir yedek geri yüklendiğinde veritabanı bozuk çıkabilir veya son değişiklikler eksik olabilir. Yalnızca kısa bir kesintiyi bile göze alamıyorsanız kullanın.',
    bindsLabel: 'Sunucu klasörlerini dahil et',
    bindsHint: 'Uygulamaya bağlı klasörlerin içeriği de yedeğe yazılır. Büyük medya klasörleri yedeği çok büyütebilir.',
    bindsList: 'Dahil edilecek klasörler: {list}',
    willEncrypt: 'Bu yedek şifrelenecek.',
    wontEncrypt: 'Bu yedek şifrelenmeyecek ve gizli bilgileri açık olarak içerecek.',
    start: 'Yedeklemeyi Başlat',
    backupStarted: '{name} için yedekleme başlatıldı.',

    // Jobs
    jobsTitle: 'Süren ve son işlemler',
    jobBackup: 'Yedekleme',
    jobRestore: 'Geri yükleme',
    jobVerify: 'Doğrulama',
    jobImport: 'İçe aktarma',
    jobCancel: 'İptal Et',
    jobCancelRequested: 'İptal isteniyor…',
    jobCancelled: 'İptal isteği gönderildi.',
    jobNotCancellable: 'Bu işlem artık iptal edilemez: verilerin üzerine yazılıyor. Yarıda kesmek uygulamayı bozuk bırakır; bitmesini bekleyin.',
    jobProcessed: '{done} işlendi',
    jobProcessedOf: '{done} / yaklaşık {total}',
    jobLogs: 'Ayrıntılar',
    jobSurvives: 'İşlemler sunucuda çalışır; bu sayfayı veya tarayıcıyı kapatmanız onları durdurmaz.',
    streamLost: 'Canlı bağlantı kurulamadı. Durum, bağlantı geri geldiğinde güncellenir.',

    // Status / labels
    stRunning: 'Sürüyor',
    stSuccess: 'Başarılı',
    stFailed: 'Başarısız',
    stCancelled: 'İptal edildi',
    stMissing: 'Dosya yok',
    trManual: 'Elle',
    trScheduled: 'Zamanlanmış',
    trSafety: 'Güvenlik yedeği',
    trImported: 'İçe aktarıldı',
    consStopped: 'Tutarlı (uygulama durdurularak)',
    consLive: 'Çalışırken alındı',
    consStoppedShort: 'Tutarlı',
    consLiveShort: 'Çalışırken',
    encrypted: 'Şifreli',
    unencrypted: 'Şifresiz',
    verifiedOk: 'Doğrulandı: {time}',
    verifiedBad: 'Doğrulama başarısız: {time}',
    notVerified: 'Doğrulanmadı',
    warningsCount: '{count} uyarı',

    // List
    listTitle: 'Tüm yedekler',
    filterApp: 'Uygulama',
    filterStatus: 'Durum',
    filterTrigger: 'Tür',
    all: 'Tümü',
    colApp: 'Uygulama',
    colDate: 'Tarih',
    colSize: 'Boyut',
    colDuration: 'Süre',
    colStatus: 'Durum',
    colType: 'Tür',
    colActions: 'İşlemler',
    listEmptyTitle: 'Yedek yok',
    listEmptyDesc: 'Henüz hiç yedek alınmadı veya seçtiğiniz süzgeçlere uyan yedek yok.',
    details: 'Ayrıntılar',
    detailsTitle: 'Yedek ayrıntıları',
    fileName: 'Dosya',
    errorLabel: 'Hata',
    warningsLabel: 'Uyarılar',
    includesBinds: 'Sunucu klasörleri',
    included: 'Dahil',
    excluded: 'Dahil değil',

    // Delete
    deleteTitle: 'Yedeği sil',
    deleteMsg: '{name} uygulamasının {time} tarihli yedeği kalıcı olarak silinecek.',
    deleteWarn: 'Silinen yedek geri getirilemez. Bu uygulamanın başka yedeği yoksa verileri geri yükleyemezsiniz.',
    deleteRecordMsg: '{name} uygulamasının {time} tarihli başarısız yedekleme kaydı silinecek.',
    deleted: 'Yedek silindi.',

    // Verify
    verifyStarted: 'Doğrulama başlatıldı.',
    passphraseTitle: 'Parola gerekli',
    passphraseLabel: 'Yedeğin parolası',
    passphraseHint:
      'Bu yedek, sunucuda kayıtlı anahtarla açılamıyor. Yedek alınırken geçerli olan parolayı girin. Girdiğiniz parola her zaman denetlenir; yanlışsa işlem başlamaz. Parola kaydedilmez.',
    continue: 'Devam',

    // Restore
    restoreTitle: 'Geri yükle: {name}',
    restorePick: 'Geri yüklenecek yedek',
    restoreNoBackups: 'Bu uygulamanın geri yüklenebilir bir yedeği yok.',
    restoreVerify: 'Doğrula ve İncele',
    restoreVerifying: 'Yedek doğrulanıyor. Dosyanın tamamı okunuyor ve sağlama toplamları denetleniyor…',
    restoreVerifyFailed: 'Yedek doğrulanamadı; geri yükleme yapılamaz.',
    restoreVerified: 'Yedek okunabilir durumda ve sağlama toplamları eşleşiyor.',
    restoreLiveWarn: 'Bu yedek uygulama çalışırken alınmış. Veritabanı dosyaları tutarsız olabilir.',
    restoreWhat: 'Geri yüklenecekler',
    restoreConfig: 'Uygulama yapılandırması (portlar, ortam değişkenleri ve {count} gizli değer)',
    restoreVersion: 'Yedekteki sürüm: {version}',
    restoreInstalledVersion: 'Kurulu sürüm: {version}',
    restoreImages: 'Görüntüler: {list}',
    kindVolume: 'Veri birimi',
    kindBind: 'Klasör',
    willOverwrite: 'Mevcut içerik silinip üzerine yazılacak',
    willCreate: 'Yeniden oluşturulacak',
    entrySize: '{files} dosya, {size}',
    untouched: 'Yedekte verisi olmayan ve olduğu gibi bırakılacak konumlar: {list}',
    notInstalledInfo: 'Uygulama şu anda kurulu değil. Geri yükleme, uygulamayı yedekteki yapılandırmayla yeniden kurar.',
    installedInfo: 'Uygulama durdurulacak, verileri yedektekilerle değiştirilecek, ardından yedekteki yapılandırmayla yeniden oluşturulup başlatılacak.',
    safetyLabel: 'Önce mevcut durumun güvenlik yedeğini al',
    safetyHint: 'Önerilir. Geri yükleme istediğiniz sonucu vermezse bu yedekle önceki duruma dönebilirsiniz.',
    safetyOffWarn: 'Güvenlik yedeği olmadan geri yükleme geri alınamaz.',
    restoreBindsLabel: 'Sunucu klasörlerini de geri yükle',
    restoreBindsHint: 'Kapatırsanız klasörlerin bugünkü içeriğine dokunulmaz; yalnızca veri birimleri ve yapılandırma geri yüklenir.',
    restoreGo: 'Geri Yüklemeyi Başlat',
    confirmTitle: 'Geri yüklemeyi onaylayın',
    confirmMsg: '{name} uygulamasının şu anki verileri silinecek ve {time} tarihli yedekteki verilerle değiştirilecek.',
    confirmWarn: 'Veriler yazılmaya başladıktan sonra işlem iptal edilemez. O andan itibaren geri yükleme ya tamamlanır ya da başarısız olur.',
    restoreRunning: 'Geri yükleme sürüyor',
    restoreDone: 'Geri yükleme tamamlandı. Uygulama çalışıyor.',
    restoreFailed: 'Geri yükleme başarısız oldu',
    restoreCancelled: 'Geri yükleme iptal edildi. Hiçbir veri değiştirilmedi.',
    restoredList: 'Geri yüklenenler: {list}',
    skippedList: 'Dokunulmayanlar: {list}',
    safetyFile: 'Güvenlik yedeği: {file}',
    back: 'Geri',

    // Schedule
    scheduleTitle: 'Zamanlama: {name}',
    scheduleEnabled: 'Zamanlanmış yedekleme',
    frequency: 'Sıklık',
    freqDaily: 'Her gün',
    freqWeekly: 'Her hafta',
    freqMonthly: 'Her ay',
    time: 'Saat',
    timeHint: 'Sunucunun yerel saatine göre.',
    weekday: 'Haftanın günü',
    monthday: 'Ayın günü',
    monthdayHint: 'Ay daha kısaysa ayın son günü kullanılır.',
    keepLast: 'Saklanacak yedek sayısı',
    keepLastHint: 'En yeni yedekler saklanır, daha eski zamanlanmış yedekler silinir.',
    pruneManual: 'Elle alınan yedekleri de say ve sil',
    pruneManualHint: 'Kapalıyken elle alınan yedekler hiçbir zaman otomatik silinmez. Güvenlik yedekleri ve içe aktarılanlar her durumda korunur.',
    missedInfo: 'Sunucu kapalıyken kaçan yedeklemeler, sunucu açıldığında bir kez çalıştırılır.',
    scheduleEncWarn: 'Zamanlanmış yedekler de şifrelenir. Bunun için paroladan türetilen anahtar sunucuda saklanır; ayrıntılar Ayarlar > Yedekleme bölümündedir.',
    scheduleSaved: 'Zamanlama kaydedildi.',
    invalidNumber: 'Geçerli bir sayı girin.',
    d0: 'Pazar',
    d1: 'Pazartesi',
    d2: 'Salı',
    d3: 'Çarşamba',
    d4: 'Perşembe',
    d5: 'Cuma',
    d6: 'Cumartesi',
    sumDaily: 'Her gün {time}',
    sumWeekly: 'Her {day} {time}',
    sumMonthly: 'Her ayın {day}. günü {time}',

    // Upload
    uploadTitle: 'Yedek dosyası yükle',
    uploadDesc: 'MyServer tarafından oluşturulmuş bir yedek dosyasını (.tar.gz veya .tar.gz.enc) yükleyin. Dosya, kabul edilmeden önce baştan sona doğrulanır.',
    uploadPick: 'Dosya seç',
    uploadFile: 'Yedek dosyası',
    uploadStart: 'Yükle ve Doğrula',
    uploading: 'Yükleniyor… {percent}',
    uploadValidating: 'Dosya doğrulanıyor…',
    uploadDone: 'Yedek içe aktarıldı: {name}',
    uploadFailed: 'Dosya kabul edilmedi',
    uploadUntrusted: 'Yalnızca kaynağına güvendiğiniz yedekleri yükleyin. Geri yüklenen bir yedek, uygulamanın yapılandırmasını ve tüm verilerini belirler.',

    // Settings
    setTitle: 'Yedekleme',
    setSubtitle: 'Varsayılanlar, şifreleme ve yedek klasörü',
    setRetention: 'Varsayılan saklama sayısı',
    setRetentionHint: 'Yeni zamanlamalarda önerilen, saklanacak yedek sayısı.',
    setConsistency: 'Varsayılan yedekleme biçimi',
    setConsStopped: 'Uygulamayı durdurarak (tutarlı, önerilen)',
    setConsLive: 'Çalışırken (kesintisiz, tutarsızlık riski var)',
    setBinds: 'Sunucu klasörlerini varsayılan olarak dahil et',
    setMinFree: 'Boş alan uyarı eşiği (GB)',
    setMinFreeHint: 'Yedek klasöründeki boş alan bunun altına düşerse sistem sağlığında uyarı gösterilir.',
    setSaved: 'Yedekleme ayarları kaydedildi.',
    setDir: 'Yedek klasörü',
    setFree: 'Boş alan',
    setUsed: 'Yedeklerin kapladığı alan',
    setFreeUnknown: 'Okunamadı',
    setFreeOf: '{free} boş / {total}',
    setEncTitle: 'Şifreleme parolası',
    setEncOn: 'Açık. Parola {time} tarihinde belirlendi. Bundan sonra alınan tüm yedekler şifrelenir.',
    setEncOff: 'Kapalı. Yedekler şifresiz yazılıyor.',
    setEncHowTitle: 'Parola nasıl saklanır?',
    setEncHow:
      'Parolanın kendisi hiçbir yere kaydedilmez ve loglara yazılmaz. Zamanlanmış yedeklerin size sormadan şifrelenebilmesi için paroladan Argon2id ile türetilen anahtar, sunucuda {file} dosyasında (yalnızca panel kullanıcısının okuyabildiği, 0600 izinli) saklanır.',
    setEncImply:
      'Sonuç: Sunucuda yönetici (root) yetkisi olan veya bu dosyayı okuyabilen biri yedekleri açabilir. Şifreleme, sunucudan dışarı çıkan yedek dosyalarını (indirilenler, başka disklere veya buluta kopyalananlar) korur; sunucuyu ele geçirmiş birine karşı koruma sağlamaz.',
    setEncForget: 'Parolayı unutursanız ve bu sunucudaki anahtar dosyası kaybolursa şifreli yedekler bir daha açılamaz. Parolayı güvenli bir yere not edin.',
    setEncNew: 'Yeni parola',
    setEncRepeat: 'Yeni parola (tekrar)',
    setEncShort: 'Parola en az 12 karakter olmalıdır.',
    setEncMismatch: 'Parolalar aynı değil.',
    setEncSet: 'Parolayı Belirle',
    setEncChange: 'Parolayı Değiştir',
    setEncChangeInfo: 'Parolayı değiştirmek eski yedekleri yeniden şifrelemez: eski yedekler alındıkları zamanki parolayla açılır ve geri yüklenirken o parola sorulur.',
    setEncDisable: 'Şifrelemeyi Kapat',
    setEncDisableTitle: 'Şifrelemeyi kapat',
    setEncDisableMsg: 'Sunucudaki anahtar silinecek ve bundan sonra alınan yedekler şifresiz yazılacak.',
    setEncDisableWarn: 'Mevcut şifreli yedekler şifreli kalır; onları açmak için parolayı girmeniz gerekecek.',
    setEncSaved: 'Şifreleme parolası belirlendi.',
    setEncCleared: 'Şifreleme kapatıldı.',
  },
})
