import { messages } from '@/i18n'

export const t = messages({
  tr: {
    pageTitle: 'Güncellemeler',
    pageDescription: 'Ubuntu paketleri, Docker imajları ve MyServer sürümü. Hiçbir güncelleme onayınız olmadan yüklenmez.',
    check: 'Denetle',
    checking: 'Denetleniyor…',
    checkDone: 'Denetim tamamlandı.',
    lastCheck: 'Son denetim: {time}',
    neverChecked: 'Henüz denetlenmedi',
    autoOff: 'Otomatik denetim kapalı',
    upToDate: 'Güncel',
    updatesCount: '{count} güncelleme',
    updatesAvailable: '{count} güncelleme mevcut',
    adminOnly: 'Bu işlem için yönetici yetkisi gerekir.',
    cancel: 'Vazgeç',
    viewAll: 'Tümünü Gör',

    // Ubuntu
    aptTitle: 'Ubuntu Paketleri',
    aptListsRefreshed: 'Paket listeleri yenilendi: {time}',
    aptEmptyTitle: 'Tüm paketler güncel',
    aptEmptyDesc: 'Son denetimde yüklenecek bir paket güncellemesi bulunmadı.',
    aptNeverTitle: 'Paketler henüz denetlenmedi',
    aptNeverDesc: 'Güncellemeleri görmek için "Denetle" düğmesini kullanın.',
    aptStale: 'Aşağıdaki liste son başarılı denetime aittir.',
    colPackage: 'Paket',
    colCurrent: 'Kurulu sürüm',
    colCandidate: 'Yeni sürüm',
    badgeSecurity: 'Güvenlik',
    badgeKernel: 'Çekirdek',
    badgeNew: 'Yeni paket',
    securityCount: '{count} güvenlik güncellemesi',
    kernelCount: '{count} çekirdek paketi',
    optionsTitle: 'Yükleme seçenekleri',
    modeLabel: 'Yükseltme türü',
    modeUpgrade: 'Standart yükseltme (önerilen)',
    modeFull: 'Tam yükseltme (dist-upgrade)',
    modeUpgradeHint: 'Hiçbir paketi kaldırmaz. Kaldırma gerektiren güncellemeler bekletilir.',
    modeFullHint: 'Bağımlılık değişiklikleri gerekiyorsa kurulu paketleri kaldırabilir. Yalnızca ne yaptığınızı biliyorsanız seçin.',
    kernelOption: 'Çekirdek güncellemelerini de yükle',
    kernelHint: 'Kapalıyken çekirdek paketleri (linux-image, linux-headers…) yüklenmez. Çekirdek güncellemesi yeniden başlatma gerektirir.',
    install: 'Güncellemeleri Yükle',
    confirmTitle: 'Paket güncellemeleri yüklensin mi?',
    confirmMessage: 'Seçilen güncellemeler şimdi yüklenecek. İşlem arka planda çalışır; tarayıcıyı kapatsanız da devam eder.',
    confirmKernelOn: 'Çekirdek paketleri de yüklenecek. Yeni çekirdek, sunucu yeniden başlatılana kadar etkin olmaz; panel sunucuyu kendiliğinden yeniden başlatmaz.',
    confirmKernelOff: 'Çekirdek paketleri yüklenmeyecek.',
    confirmFull: 'Tam yükseltme seçildi: bazı paketler kaldırılabilir.',
    confirmInstall: 'Yükle',
    upgradeStarted: 'Paket güncellemesi başlatıldı.',
    upgradeRunning: 'Paket güncellemesi sürüyor',
    upgradeOk: 'Paket güncellemesi tamamlandı.',
    upgradeFailed: 'Paket güncellemesi başarısız oldu.',
    rebootTitle: 'Yeniden başlatma gerekiyor',
    rebootDesc: 'Yüklenen güncellemelerin etkin olması için sunucu yeniden başlatılmalı. Panel bunu kendiliğinden yapmaz.',
    rebootPackages: 'Yeniden başlatma isteyen paketler: {list}',
    reboot: 'Yeniden Başlat',
    rebootConfirmTitle: 'Sunucu yeniden başlatılsın mı?',
    rebootConfirmMessage: 'Sunucu hemen yeniden başlatılacak. Çalışan tüm uygulamalar ve bağlantılar kesilir; panel birkaç dakika erişilemez olur.',
    rebootStarted: 'Sunucu yeniden başlatılıyor.',

    // Jobs
    outputTitle: 'İşlem çıktısı',
    outputWaiting: 'Çıktı bekleniyor…',
    outputLive: 'Canlı',
    jobRunning: 'Sürüyor',
    jobSuccess: 'Başarılı',
    jobFailed: 'Başarısız',
    jobStartedBy: '{user} tarafından, {time}',
    lastJob: 'Son işlem',
    showOutput: 'Çıktıyı göster',
    hideOutput: 'Çıktıyı gizle',

    // Docker
    dockerTitle: 'Docker İmajları',
    dockerEmptyTitle: 'Denetlenecek imaj yok',
    dockerEmptyDesc: 'Bu sunucuda konteyner bulunmuyor.',
    dockerNeverTitle: 'İmajlar henüz denetlenmedi',
    dockerNeverDesc: 'Konteynerlerin imajlarını kayıt defteriyle karşılaştırmak için "Denetle" düğmesini kullanın.',
    colImage: 'İmaj',
    colUsedBy: 'Kullanan konteynerler',
    colApp: 'Uygulama',
    colStatus: 'Durum',
    colAction: 'İşlem',
    imgCurrent: 'Güncel',
    imgUpdate: 'Güncelleme mevcut',
    imgUnchecked: 'Denetlenemedi',
    imgPulled: 'İndirildi',
    imgPulledHint: 'Yeni imaj indirildi; kullanılması için konteyner yeniden oluşturulmalı.',
    uncheckedCount: '{count} imaj denetlenemedi',
    pull: 'İmajı İndir',
    pullConfirmTitle: 'Yeni imaj indirilsin mi?',
    pullConfirmMessage: '{image} imajının yeni sürümü indirilecek. Çalışan konteynerler değiştirilmez; yeni imajın kullanılması için konteyner yeniden oluşturulmalıdır.',
    pullStarted: 'İmaj indirme başlatıldı.',
    pullOk: 'İmaj indirildi. Konteyneri yeniden oluşturmayı unutmayın.',
    pullFailed: 'İmaj indirilemedi.',
    openApps: 'Uygulamalarda güncelle',
    openDocker: 'Docker’da yönet',
    dockerNote: 'İmajı indirmek çalışan konteynerleri değiştirmez. Güncellemeyi uygulamak için konteyner, Uygulamalar veya Docker sayfasından yeniden oluşturulur.',

    // Self
    selfTitle: 'MyServer',
    selfWidgetName: 'MyServer Panel',
    installedVersion: 'Kurulu sürüm',
    latestVersion: 'Yayınlanan son sürüm',
    source: 'Güncelleme kaynağı',
    published: 'Yayın tarihi',
    checksum: 'Sağlama toplamı (SHA-256)',
    checksumMissing: 'Kaynak bildirmedi.',
    archive: 'Kurulum arşivi ({arch})',
    notInstallableTitle: 'Bu güncelleme panelden yüklenemez',
    lastUpdateTitle: 'Son MyServer güncellemesi',
    lastRunning: 'Güncelleme sürüyor: {to} sürümü kuruluyor.',
    lastSuccess: '{to} sürümüne güncelleme başarıyla tamamlandı.',
    lastFailed: '{to} sürümüne güncelleme başarısız oldu.',
    lastRolledBack: '{to} sürümüne güncelleme başarısız oldu; önceki sürüme ({from}) geri dönüldü.',
    lastWhen: 'Zaman: {time}',
    noSourceTitle: 'Güncelleme kaynağı yapılandırılmamış',
    noSourceDesc: 'MyServer için bir sürüm kaynağı tanımlı değil, bu yüzden yeni sürüm denetimi yapılmadı. Kaynak, Ayarlar bölümünden tanımlanabilir.',
    selfNotChecked: 'Bu kaynak henüz denetlenmedi.',
    selfCurrent: 'MyServer güncel.',
    selfAvailable: 'MyServer {version} sürümü mevcut.',
    releaseNotes: 'Sürüm notları',
    noNotes: 'Bu sürüm için not yayınlanmamış.',
    selfInstall: 'MyServer’ı Güncelle',
    selfConfirmTitle: 'MyServer güncellensin mi?',
    selfConfirmMessage: 'MyServer {from} sürümünden {to} sürümüne güncellenecek. Panel güncelleme sırasında yeniden başlar ve kısa süre erişilemez olur.',
    selfStarted: 'Güncelleme başlatıldı. Panel birazdan yeniden başlayacak.',
    vCurrent: 'v{version} (Güncel)',
    vAvailable: 'v{version} mevcut',
    vOnly: 'v{version}',

    // Widget
    widgetTitle: 'Güncellemeler',
    widgetDocker: 'Docker',
    review: 'Güncellemeleri İncele',
    nothingToUpdate: 'Yüklenecek güncelleme yok',
    notChecked: 'Denetlenmedi',
    checkFailed: 'Denetlenemedi',
    rebootShort: 'Yeniden başlatma gerekiyor',

    // Settings
    settingsTitle: 'Güncellemeler',
    settingsSubtitle: 'Denetim zamanlaması ve MyServer sürüm kaynağı. Güncellemeler hiçbir zaman kendiliğinden yüklenmez.',
    intervalLabel: 'Denetim aralığı (saat)',
    intervalHint: '1 ile 720 saat arasında. Varsayılan: 24 (günde bir).',
    intervalInvalid: 'Denetim aralığı 1 ile 720 arasında bir sayı olmalıdır.',
    autoApt: 'Ubuntu paketlerini otomatik denetle',
    autoDocker: 'Docker imajlarını otomatik denetle',
    autoSelf: 'MyServer sürümünü otomatik denetle',
    autoHint: 'Otomatik denetim yalnızca bilgi toplar; hiçbir şey yüklemez.',
    sourceLabel: 'MyServer sürüm kaynağı',
    sourceNone: 'Yok (denetleme yapılmaz)',
    sourceGithub: 'GitHub Releases',
    sourceUrl: 'Kendi güncelleme sunucum (JSON bildirimi)',
    repoLabel: 'GitHub deposu',
    repoHint: '"sahip/depo" biçiminde.',
    repoRequired: 'GitHub deposu girilmelidir.',
    urlLabel: 'Bildirim adresi',
    urlHint: 'HTTPS üzerinden sunulan JSON dosyasının adresi.',
    urlRequired: '"https://" ile başlayan bir adres girilmelidir.',
    save: 'Kaydet',
    saved: 'Güncelleme ayarları kaydedildi.',
  },
})
