import { messages } from '@/i18n'

export const t = messages({
  tr: {
    title: 'Uygulamalar',
    pageDescription: 'Kurulu uygulamalarınızı yönetin, mağazadan tek tıkla yenilerini kurun.',
    tabInstalled: 'Kurulu',
    tabStore: 'Mağaza',
    tabsLabel: 'Uygulama görünümü',
    categoriesLabel: 'Kategori',
    all: 'Tümü',
    installApp: 'Uygulama Kur',
    search: 'Uygulama ara…',
    searchLabel: 'Uygulama ara',
    gridView: 'Izgara görünümü',
    listView: 'Liste görünümü',
    reload: 'Yenile',
    reloadDone: 'Katalog yenilendi: {valid} uygulama yüklendi.',
    reloadInvalid: 'Katalog yenilendi: {valid} uygulama yüklendi, {invalid} tanım geçersiz.',

    loadingApps: 'Uygulamalar yükleniyor…',
    emptyInstalledTitle: 'Henüz kurulu uygulama yok',
    emptyInstalledText: 'Mağazadan bir uygulama seçip birkaç adımda kurabilirsiniz.',
    emptyInstalledUser: 'Uygulamaları yalnızca yöneticiler kurabilir.',
    emptyFilterTitle: 'Eşleşen uygulama yok',
    emptyFilterText: 'Aramayı veya kategori filtresini değiştirin.',
    emptyStoreTitle: 'Katalog boş',
    emptyStoreText: 'Uygulama tanımları klasöründe geçerli bir tanım dosyası bulunamadı.',
    openStore: 'Mağazayı Aç',
    dockerDown: 'Docker servisine ulaşılamıyor.',
    dockerDownText: 'Uygulamaların durumu okunamıyor. Docker servisinin çalıştığını kontrol edin.',
    invalidTitle: 'Geçersiz uygulama tanımları',
    invalidText: 'Aşağıdaki dosyalar atlandı. Düzelttikten sonra Yenile düğmesine basın.',

    stateRunning: 'Çalışıyor',
    stateStopped: 'Durduruldu',
    stateStarting: 'Başlatılıyor',
    stateUnhealthy: 'Sağlıksız',
    statePartial: 'Kısmen çalışıyor',
    stateMissing: 'Konteyner bulunamadı',
    stateUnknown: 'Durum bilinmiyor',
    opInstall: 'Kuruluyor…',
    opUpdate: 'Güncelleniyor…',
    opSettings: 'Ayarlar uygulanıyor…',
    opRestore: 'Geri yükleniyor…',
    opStart: 'Başlatılıyor…',
    opStop: 'Durduruluyor…',
    opRestart: 'Yeniden başlatılıyor…',
    opUninstall: 'Kaldırılıyor…',
    opBusy: 'İşlem sürüyor…',

    menuLabel: '{name} işlemleri',
    open: 'Aç',
    start: 'Başlat',
    stop: 'Durdur',
    restart: 'Yeniden Başlat',
    update: 'Güncelle',
    logs: 'Loglar',
    settings: 'Ayarlar',
    uninstall: 'Kaldır',
    progress: 'İlerlemeyi Göster',
    details: 'Ayrıntılar',

    started: '{name} başlatıldı.',
    stopped: '{name} durduruldu.',
    restarted: '{name} yeniden başlatıldı.',

    install: 'Kur',
    installed: 'Kurulu',
    installing: 'Kuruluyor',
    installTitle: '{name} Kurulumu',
    settingsTitle: '{name} Ayarları',
    detailsTitle: '{name}',
    adminOnly: 'Uygulamaları yalnızca yöneticiler kurabilir.',
    website: 'Web sitesi',
    version: 'Sürüm',
    images: 'Görüntüler',
    notes: 'Kurulum notları',
    securityWarnings: 'Güvenlik uyarıları',
    acceptRisks: 'Uyarıları okudum, riskleri kabul ediyorum.',
    acceptRisksRequired: 'Devam etmek için güvenlik uyarılarını kabul etmelisiniz.',
    sectionPorts: 'Portlar',
    sectionEnv: 'Ayarlar',
    sectionPaths: 'Klasörler',
    sectionVolumes: 'Veri birimleri',
    sectionAccess: 'Ağ erişimi',
    exposureTitle: 'Bu portlar ağa açılır',
    exposureText:
      'Aşağıdaki portlara, bu sunucuya ağ üzerinden ulaşabilen her cihaz erişebilir. Panelin güvenlik duvarı (UFW) kuralları Docker tarafından yayınlanan portları kısıtlamaz. Sunucunun genel (public) bir IP adresi varsa veya modeminiz bu sunucuya port yönlendiriyorsa uygulamaya internetten de erişilebilir.',
    exposureHostTitle: 'Uygulama sunucunun ağını doğrudan kullanır',
    exposureHostText:
      'Bu uygulama sunucunun ağını doğrudan kullanır; açtığı tüm portlar aynı şekilde ağdaki her cihaza açıktır ve sunucu internete açıksa internetten de erişilebilir. Panelin güvenlik duvarı (UFW) kurallarına güvenmeden önce bunları denetleyin.',
    exposureLoopback:
      'Portlar yalnızca 127.0.0.1 adresinde yayınlanır; uygulamaya ağdaki diğer cihazlardan erişilemez.',
    loopbackOnly: 'Yalnızca bu sunucudan erişilsin (127.0.0.1)',
    loopbackOnlyText:
      'Açıldığında uygulamaya yalnızca sunucunun kendisinden erişilebilir; örneğin bir ters vekil sunucu (reverse proxy) veya SSH tüneli üzerinden. "Aç" bağlantısı diğer cihazlardan çalışmaz.',
    loopbackHostNote: 'Sunucunun ağını doğrudan kullanan servisler bu ayardan etkilenmez.',
    publishedPorts: 'Yayınlanan portlar',
    addrAll: 'tüm ağ arayüzleri',
    addrLoopback: 'yalnızca bu sunucu',
    addrHost: 'sunucu ağı',
    openLocalOnly: 'Aç (yalnızca sunucudan erişilebilir)',
    localOnlyHint: 'Bu uygulama yalnızca 127.0.0.1 adresinde yayınlanıyor; başka cihazlardan açılamaz.',
    exposedAll: 'Ağa açık',
    exposedLocal: 'Yalnızca sunucu',
    sectionOptions: 'İsteğe bağlı yetkiler',
    optionCaps: 'Açıldığında verilen yetki: {caps}',
    browse: 'Gözat',
    browseTitle: '{label} için klasör seçin',
    browseConfirm: 'Bu Klasörü Seç',
    unsupported: 'Desteklenmiyor',
    architectures: 'Mimariler',
    portHint: 'Konteyner portu {container}/{protocol}',
    portFixed: 'Bu uygulama sunucunun ağını doğrudan kullandığı için port değiştirilemez.',
    portInvalid: 'Port 1 ile 65535 arasında olmalıdır.',
    required: 'Bu alan zorunludur.',
    secretKeep: 'Değiştirmek istemiyorsanız boş bırakın.',
    secretGenerated: 'Boş bırakırsanız rastgele bir değer üretilir.',
    secretStored: 'Kayıtlı bir değer var',
    showSecret: 'Değeri göster',
    hideSecret: 'Değeri gizle',
    pathHint: 'Konteynerde {target} olarak görünür. İzin verilen klasörler: {roots}',
    pathOptional: 'Boş bırakılırsa bu klasör bağlanmaz.',
    pathInvalid: 'Mutlak bir klasör yolu girin (örnek: /data/medya).',
    readOnly: 'salt okunur',
    volumeNamed: 'Docker birimi',
    volumeSystem: 'Sistem yolu',
    startInstall: 'Kurulumu Başlat',
    applySettings: 'Kaydet ve Yeniden Oluştur',
    settingsWarning: 'Ayarlar kaydedildiğinde uygulamanın konteynerleri yeniden oluşturulur; uygulama kısa süre durur. Verileriniz korunur.',
    manifestMissing: 'Bu uygulamanın tanım dosyası artık katalogda yok; ayarları değiştirilemez.',
    cancel: 'Vazgeç',
    close: 'Kapat',
    noFields: 'Bu uygulamanın değiştirilebilir ayarı yok.',

    jobInstall: 'Kurulum',
    jobUpdate: 'Güncelleme',
    jobSettings: 'Ayar değişikliği',
    jobRestore: 'Geri yükleme',
    jobTitle: '{name}: {kind}',
    jobRunning: 'İşlem sürüyor. Bu pencereyi veya tarayıcıyı kapatabilirsiniz; işlem sunucuda devam eder.',
    jobSuccess: 'İşlem başarıyla tamamlandı.',
    jobFailed: 'İşlem başarısız oldu',
    jobWaiting: 'Sunucudan ilerleme bilgisi bekleniyor…',
    jobStreamLost: 'İlerleme akışına bağlanılamıyor. İşlem sunucuda devam ediyor olabilir.',
    jobRetry: 'Yeniden Bağlan',
    jobDetails: 'Ayrıntılar',
    downloadProgress: '{current} / {total}',
    installStarted: '{name} kurulumu başladı.',
    installDone: '{name} kuruldu.',

    updateTitle: '{name} güncellensin mi?',
    updateMessage: 'Uygulamanın en yeni görüntüsü indirilir ve konteynerleri yeniden oluşturulur. Ayarlarınız ve verileriniz korunur; uygulama kısa süre durur.',
    updateWarning: 'Yeni sürüm başlatılamazsa önceki sürüm geri yüklenir. Önemli verileriniz için güncellemeden önce yedek almanız önerilir.',
    updateConfirm: 'Güncelle',

    stopTitle: '{name} durdurulsun mu?',
    stopMessage: 'Uygulama durdurulur ve yeniden başlatılana kadar erişilemez. Verileriniz korunur.',

    uninstallTitle: '{name} kaldırılsın mı?',
    uninstallMessage: 'Uygulamanın konteynerleri ve özel ağı kaldırılır.',
    uninstallChoice: 'Uygulama verileri',
    keepData: 'Verileri koru (önerilen)',
    keepDataText: 'Veri birimleri sunucuda kalır. Uygulamayı yeniden kurduğunuzda kaldığı yerden devam eder.',
    deleteData: 'Veri birimlerini de sil',
    deleteDataText: 'Uygulamanın Docker veri birimleri kalıcı olarak silinir. Bu işlem geri alınamaz.',
    volumesToDelete: 'Silinecek veri birimleri',
    pathsKept: 'Seçtiğiniz klasörler hiçbir durumda silinmez',
    noVolumes: 'Bu uygulamanın Docker veri birimi yok.',
    continue: 'Devam Et',
    uninstallConfirmTitle: '{name} kaldırılıyor',
    uninstallConfirmKeep: 'Uygulama kaldırılacak, verileri korunacak.',
    uninstallConfirmDelete: 'Uygulama kaldırılacak ve tüm veri birimleri kalıcı olarak silinecek.',
    uninstallDeleteWarning: 'Bu işlem geri alınamaz. Uygulamanın içindeki tüm veriler (ayarlar, veritabanı, yüklenen dosyalar) silinir.',
    uninstalled: '{name} kaldırıldı. Verileri korundu.',
    uninstalledDeleted: '{name} ve veri birimleri kaldırıldı.',
    uninstalledPartial: '{name} kaldırıldı ancak bazı veri birimleri silinemedi: {volumes}',

    logsTitle: '{name} Logları',
    service: 'Servis',
    logsWaiting: 'Log satırı bekleniyor…',
    logsEnded: 'Konteyner durdu; log akışı sona erdi.',
    logsConnecting: 'Bağlanıyor…',
    logsLive: 'Canlı',
    logsClosed: 'Bağlantı kapalı',
    logsClear: 'Temizle',
    logsFollow: 'Otomatik kaydır',
    logsRegion: 'Uygulama logları',

    servicesTitle: 'Servisler',

    customBadge: 'Özel',
    customAdd: 'Özel Uygulama Ekle',
    customTitle: 'Özel Uygulama Ekle',
    customIntro:
      'Bir docker-compose.yml dosyasını yapıştırın veya yükleyin. Dosya panelin uygulama tanımına dönüştürülür; desteklenmeyen her ayar listelenir. Kaydettikten sonra uygulamayı mağazadan diğer uygulamalar gibi kurarsınız.',
    customTrust:
      'Compose dosyaları internetten kopyalanmış olabilir. Önizlemedeki görüntüleri, klasörleri ve güvenlik uyarılarını dikkatle inceleyin; yalnızca güvendiğiniz uygulamaları ekleyin.',
    customName: 'Uygulama adı',
    customNameHint: 'Mağazada görünen ad. Boş bırakılırsa compose dosyasındaki name alanı kullanılır.',
    customCompose: 'docker-compose.yml içeriği',
    customComposeHint: 'En fazla {size}. Yalnızca hazır görüntüler (image) desteklenir.',
    customFile: 'Dosyadan Yükle',
    customFileTooBig: 'Dosya çok büyük (en fazla {size}).',
    customFileType: 'Yalnızca .yml veya .yaml dosyaları yüklenebilir.',
    customFileUnreadable: 'Dosya okunamadı.',
    customFileLoaded: '{name} yüklendi.',
    customComposeRequired: 'Compose dosyasının içeriğini girin.',
    customTooBig: 'İçerik çok büyük (en fazla {size}).',
    customPreview: 'Önizle',
    customSave: 'Kaydet',
    customBack: 'Düzenle',
    customProblems: 'Compose dosyası kabul edilmedi',
    customProblemsHint: 'Aşağıdaki sorunları düzeltip yeniden önizleyin.',
    customSummary: 'Özet',
    customServices: 'Servisler ve görüntüler',
    customPorts: 'Portlar',
    customVolumes: 'Veri birimleri',
    customFolders: 'Klasörler',
    customEnv: 'Kurulumda sorulacak ayarlar',
    customNotes: 'Dönüştürme notları',
    customNoPorts: 'Port yayınlanmıyor.',
    customNoVolumes: 'Kalıcı veri birimi yok.',
    customNoEnv: 'Ortam değişkeni yok.',
    customDependsOn: 'bağımlı: {services}',
    customRequired: 'zorunlu',
    customSecret: 'gizli',
    customGenerated: 'boşsa üretilir',
    customWebUI: 'web arayüzü',
    customLoopback: 'Portlar varsayılan olarak yalnızca 127.0.0.1 adresinde yayınlanır.',
    customRiskNote: 'Bu uygulamayı kurarken bu uyarıları ayrıca kabul etmeniz istenecek.',
    customYaml: 'Oluşturulan uygulama tanımını göster',
    customSaved: '{name} mağazaya eklendi. Şimdi kurabilirsiniz.',
    customDelete: 'Tanımı Sil',
    customDeleteTitle: '{name} tanımı silinsin mi?',
    customDeleteMessage: 'Özel uygulamanın tanımı mağazadan kaldırılır. Uygulama kurulu olmadığı için hiçbir konteyner veya veri etkilenmez.',
    customDeleted: '{name} tanımı silindi.',
    customMenu: '{name} işlemleri',
  },
})
