import { messages } from '@/i18n'

export const t = messages({
  tr: {
    title: 'Terminal',
    description: 'Sunucuda {user} kullanıcısının kabuğu',
    descriptionPlain: 'Sunucu komut satırı',
    loading: 'Terminal durumu alınıyor…',

    stateConnecting: 'Bağlanıyor…',
    stateOpen: 'Bağlı',
    stateClosed: 'Bağlantı kesildi',
    sessions: '{count}/{max} oturum',

    reconnect: 'Yeniden Bağlan',
    clear: 'Temizle',
    copy: 'Seçimi kopyala',
    paste: 'Panodan yapıştır',
    fontSmaller: 'Yazıyı küçült',
    fontLarger: 'Yazıyı büyüt',
    fontSize: 'Yazı boyutu {size}',
    toolbar: 'Terminal araçları',
    helperKeys: 'Yardımcı tuşlar',
    terminalLabel: 'Sunucu terminali',

    keyEsc: 'Esc',
    keyTab: 'Tab',
    keyCtrl: 'Ctrl',
    keyUp: 'Yukarı ok',
    keyDown: 'Aşağı ok',
    keyLeft: 'Sol ok',
    keyRight: 'Sağ ok',
    keyCtrlHint: 'Ctrl: sonraki tuşla birlikte gönderilir',

    copied: 'Seçim panoya kopyalandı.',
    copyEmpty: 'Kopyalanacak bir seçim yok.',
    copyFailed: 'Panoya kopyalanamadı. Tarayıcı pano erişimine izin vermiyor.',
    pasteFailed: 'Panodan okunamadı. Tarayıcınızın yapıştırma kısayolunu kullanın (Ctrl+V).',

    unsupportedTitle: 'Terminal desteklenmiyor',
    unsupportedBody: 'Panelin çalıştığı işletim sistemi terminal oturumlarını desteklemiyor.',
    notAdminTitle: 'Terminal yalnızca yöneticilere açık',
    notAdminBody: 'Terminal sunucuda komut çalıştırmaya izin verdiği için yalnızca yönetici hesapları kullanabilir.',
    disabledTitle: 'Terminal erişimi kapalı',
    disabledBody: 'Terminal erişimi yönetici tarafından kapatıldı. Ayarlar bölümünden yeniden açılabilir.',
    noUserTitle: 'Sistem kullanıcısı seçilmemiş',
    noUserBody: 'Terminalin hangi sistem kullanıcısıyla açılacağını bir yönetici Ayarlar bölümünden seçmelidir.',
    badUserTitle: 'Sistem kullanıcısı kullanılamıyor',
    badUserBody: '“{user}” kullanıcısıyla terminal açılamıyor: {reason}',
    helperTitle: 'Yardımcı servise ulaşılamıyor',
    helperBody: 'Terminali başlatan yetkili yardımcı servis çalıştırılamıyor. Panel kurulumunu kontrol edin.',
    openSettings: 'Ayarları Aç',
    retry: 'Tekrar Dene',

    overlayConnecting: 'Terminale bağlanılıyor…',
    closedExit: 'Oturum sona erdi (çıkış kodu {code}).',
    closedNoConnect: 'Terminale bağlanılamadı. Oturumunuzun açık olduğunu ve sunucunun çalıştığını kontrol edin.',
    closedLost: 'Sunucuyla bağlantı kesildi.',
    closedSilent: 'Sunucu yanıt vermediği için bağlantı kapatıldı.',
    idleWarning: 'İşlem yapılmazsa terminal {seconds} saniye içinde kapatılacak. Sürdürmek için bir tuşa basın.',

    settingsTitle: 'Terminal',
    settingsSubtitle: 'Web terminali erişimi ve oturum kuralları',
    settingsAdminOnly: 'Terminal ayarlarını yalnızca yöneticiler değiştirebilir.',
    enabledLabel: 'Terminal erişimi',
    enabledOn: 'Yöneticiler panelden terminal açabilir.',
    enabledOff: 'Terminal kapalı. Açık oturumlar birkaç saniye içinde sonlandırılır.',
    userLabel: 'Sistem kullanıcısı',
    userHint: 'Terminal bu kullanıcının kabuğunu açar. sudo yetkisi sistemin kendi sudoers kurallarına bağlıdır. Kullanıcı değiştirildiğinde açık oturumlar kapatılır.',
    userNone: 'Seçilmedi (terminal kullanılamaz)',
    userMissing: '{user} (artık uygun değil)',
    userOption: '{user} — {shell}',
    usersEmpty: 'Uygun sistem kullanıcısı bulunamadı. Kullanıcının kimliği 1000 veya üzeri olmalı ve gerçek bir kabuğu bulunmalıdır.',
    usersError: 'Sistem kullanıcıları alınamadı: {message}',
    timeoutLabel: 'Boşta kalma süresi (dakika)',
    timeoutHint: 'Bu süre boyunca tuşa basılmazsa oturum kapatılır (1–240).',
    timeoutInvalid: 'Süre 1 ile 240 dakika arasında bir tam sayı olmalıdır.',
    save: 'Kaydet',
    saved: 'Terminal ayarları kaydedildi.',
    noChanges: 'Değişiklik yok',
  },
})
