import { messages } from '@/i18n'

export const t = messages({
  tr: {
    // page
    title: 'Docker',
    subtitle: 'Konteynerler, imajlar, birimler ve ağlar',
    tabs: 'Docker bölümleri',
    tabContainers: 'Konteynerler',
    tabImages: 'İmajlar',
    tabVolumes: 'Birimler',
    tabNetworks: 'Ağlar',
    refresh: 'Yenile',
    close: 'Kapat',
    cancel: 'Vazgeç',
    retry: 'Tekrar Dene',
    search: 'Ara',
    none: '—',
    yes: 'Evet',
    no: 'Hayır',
    unavailableTitle: 'Docker servisine ulaşılamıyor',
    unavailableBody: 'Docker durmuş veya kurulu değil. Servis yeniden çalıştığında bu sayfa kendiliğinden güncellenir.',
    adminOnly: 'Bu işlem için yönetici yetkisi gerekir.',
    live: 'Canlı',
    liveOff: 'Canlı veri bağlantısı yok',

    // container list
    searchContainers: 'Konteyner veya imaj ara',
    filterLabel: 'Durum filtresi',
    filterAll: 'Tümü',
    filterRunning: 'Çalışan',
    filterStopped: 'Durmuş',
    colName: 'Ad',
    colImage: 'İmaj',
    colState: 'Durum',
    colUptime: 'Çalışma Süresi',
    colCpu: 'CPU',
    colRam: 'RAM',
    colIp: 'IP',
    colPorts: 'Portlar',
    colActions: 'İşlemler',
    noContainers: 'Konteyner yok',
    noContainersHint: 'Bu sunucuda henüz konteyner oluşturulmamış. Uygulamalar bölümünden bir uygulama kurabilirsiniz.',
    noMatch: 'Eşleşen kayıt yok',
    noMatchHint: 'Arama veya filtreyi değiştirin.',
    appBadge: 'Uygulama: {app}',
    morePorts: '+{n}',
    noPorts: 'Yok',

    stateRunning: 'Çalışıyor',
    stateExited: 'Durduruldu',
    stateFailed: 'Hata ile durdu ({code})',
    statePaused: 'Duraklatıldı',
    stateRestarting: 'Yeniden başlıyor',
    stateCreated: 'Oluşturuldu',
    stateDead: 'Bozuk',
    stateRemoving: 'Kaldırılıyor',

    actStart: 'Başlat',
    actStop: 'Durdur',
    actRestart: 'Yeniden Başlat',
    actKill: 'Zorla Durdur',
    actRemove: 'Kaldır',
    actLogs: 'Loglar',
    actInspect: 'İncele',
    actTerminal: 'Terminal',
    actMore: '{name} için diğer işlemler',

    doneStart: '"{name}" başlatıldı.',
    doneStop: '"{name}" durduruldu.',
    doneRestart: '"{name}" yeniden başlatıldı.',
    doneKill: '"{name}" zorla durduruldu.',
    doneRemove: '"{name}" kaldırıldı.',

    stopTitle: 'Konteyneri durdur',
    stopMessage: '"{name}" konteyneri durdurulacak. Sunduğu hizmet, yeniden başlatılana kadar erişilemez olur.',
    restartTitle: 'Konteyneri yeniden başlat',
    restartMessage: '"{name}" konteyneri yeniden başlatılacak. Hizmet kısa süreliğine kesilir.',
    killTitle: 'Konteyneri zorla durdur',
    killMessage: '"{name}" konteynerinin süreci hemen sonlandırılacak (SIGKILL).',
    killWarning: 'Uygulama verilerini diske yazma fırsatı bulamaz; kaydedilmemiş veriler kaybolabilir. Önce "Durdur" işlemini deneyin.',

    removeTitle: 'Konteyneri kaldır',
    removeMessage: '"{name}" konteyneri kalıcı olarak kaldırılacak. Konteynerin kendi dosya sistemindeki değişiklikler silinir.',
    removeForce: 'Çalışıyorsa zorla kaldır',
    removeForceHint: 'Konteyner çalışıyorsa önce süreci sonlandırılır.',
    removeVolumes: 'Anonim birimlerini de sil',
    removeVolumesHint: 'Konteynere ait adsız birimler ve içindeki veriler kalıcı olarak silinir. Adlandırılmış birimler korunur.',
    removeVolumesWarning: 'Bu seçenek veri kaybına yol açar ve geri alınamaz.',
    removeTypeName: 'Onaylamak için konteyner adını yazın',
    removeRunningNote: 'Konteyner şu anda çalışıyor. Kaldırmak için "zorla kaldır" seçeneğini işaretleyin veya önce durdurun.',

    // logs
    logsTitle: 'Loglar: {name}',
    logsTail: 'Satır sayısı',
    logsTailOption: 'Son {n} satır',
    logsTimestamps: 'Zaman damgası',
    logsAutoScroll: 'Otomatik kaydır',
    logsCopy: 'Kopyala',
    logsDownload: 'İndir',
    logsClear: 'Temizle',
    logsCopied: 'Loglar panoya kopyalandı.',
    logsCopyFailed: 'Panoya kopyalanamadı. Tarayıcı izin vermiyor olabilir.',
    logsEmpty: 'Henüz log satırı yok.',
    logsConnecting: 'Bağlanıyor…',
    logsLive: 'Canlı akış',
    logsEnded: 'Konteyner durduğu için log akışı sona erdi.',
    logsEndedError: 'Log akışı beklenmedik şekilde kesildi.',
    logsFailed: 'Log akışına bağlanılamadı.',
    logsLines: '{n} satır',
    logsTruncated: 'Yalnızca son {n} satır tutuluyor.',
    logsRegion: 'Konteyner log çıktısı',

    // inspect
    inspectTitle: 'İncele: {name}',
    secGeneral: 'Genel',
    secRuntime: 'Çalışma',
    secNetworks: 'Ağlar',
    secPorts: 'Portlar',
    secMounts: 'Bağlı Birimler',
    secEnv: 'Ortam Değişkenleri',
    secLabels: 'Etiketler',
    fId: 'Kimlik',
    fImage: 'İmaj',
    fCreated: 'Oluşturulma',
    fStarted: 'Başlatılma',
    fFinished: 'Durma',
    fState: 'Durum',
    fExitCode: 'Çıkış kodu',
    fHealth: 'Sağlık denetimi',
    fRestartPolicy: 'Yeniden başlatma',
    fRestartCount: 'Yeniden başlama sayısı',
    fCommand: 'Komut',
    fEntrypoint: 'Giriş noktası',
    fWorkdir: 'Çalışma dizini',
    fUser: 'Kullanıcı',
    fHostname: 'Sunucu adı',
    fNetworkMode: 'Ağ modu',
    fPrivileged: 'Ayrıcalıklı',
    fTty: 'TTY',
    fMemoryLimit: 'Bellek sınırı',
    fCpuLimit: 'CPU sınırı',
    fPlatform: 'Platform',
    fApp: 'Uygulama',
    fOom: 'Bellek yetersizliğinden sonlandı',
    unlimited: 'Sınırsız',
    cpuCores: '{n} çekirdek',
    maskedNote: 'Parola, anahtar ve benzeri gizli değerler maskelenmiştir.',
    maskedBadge: 'gizli',
    readOnly: 'salt okunur',
    gateway: 'Ağ geçidi',
    emptySection: 'Kayıt yok.',
    healthHealthy: 'Sağlıklı',
    healthUnhealthy: 'Sağlıksız',
    healthStarting: 'Başlıyor',
    healthNone: 'Tanımlı değil',

    // terminal
    termTitle: 'Terminal: {name}',
    termConnecting: 'Bağlanıyor…',
    termConnected: 'Bağlı ({shell})',
    termClosed: 'Oturum kapandı',
    termExited: 'Kabuk sona erdi (çıkış kodu {code}).',
    termExitedUnknown: 'Kabuk sona erdi.',
    termLost: 'Bağlantı kesildi.',
    termFailed: 'Terminal bağlantısı kurulamadı. Oturumunuzu ve Docker servisini kontrol edin.',
    termReconnect: 'Yeniden Bağlan',
    termEnd: 'Oturumu Kapat',
    termRegion: 'Konteyner terminali',
    termHint: 'Oturum açıkken pencere yalnızca "Oturumu Kapat" düğmesiyle kapanır.',

    // images
    searchImages: 'İmaj ara',
    colTags: 'Etiketler',
    colSize: 'Boyut',
    colCreated: 'Oluşturulma',
    colUsage: 'Kullanım',
    colId: 'Kimlik',
    noImages: 'İmaj yok',
    noImagesHint: 'Bu sunucuda indirilmiş imaj bulunmuyor.',
    untagged: 'Etiketsiz',
    inUse: 'Kullanımda',
    unused: 'Kullanılmıyor',
    usedBy: 'Kullanan: {names}',
    pullImage: 'İmaj İndir',
    pullTitle: 'İmaj indir',
    pullLabel: 'İmaj adı',
    pullPlaceholder: 'nginx:latest',
    pullHint: 'Etiket yazılmazsa "latest" indirilir. Örnek: ghcr.io/kullanici/imaj:1.2',
    pullStart: 'İndir',
    pullRunning: 'İndiriliyor…',
    pullInvalid: 'İmaj adı geçersiz.',
    pullLayers: 'Katmanlar',
    pullLost: 'İlerleme bağlantısı kesildi. İndirme arka planda sürüyor olabilir; listeyi birazdan yenileyin.',
    pullAnother: 'Başka İmaj İndir',
    pullBackground: 'Pencereyi kapatırsanız indirme arka planda devam eder.',
    layerWaiting: 'Bekliyor',
    layerPulling: 'Hazırlanıyor',
    layerDownloading: 'İndiriliyor',
    layerVerifying: 'Doğrulanıyor',
    layerDownloaded: 'İndirildi',
    layerExtracting: 'Açılıyor',
    layerComplete: 'Tamamlandı',
    layerExists: 'Zaten var',
    pruneImages: 'Etiketsizleri Temizle',
    pruneImagesTitle: 'Etiketsiz imajları temizle',
    pruneImagesMessage: 'Hiçbir konteynerin kullanmadığı, etiketsiz {n} imaj silinecek. Etiketli imajlara dokunulmaz.',
    pruneImagesNone: 'Temizlenecek etiketsiz imaj yok.',
    pruneImagesDone: 'Temizlik tamamlandı, {size} alan boşaltıldı.',
    removeImageTitle: 'İmajı kaldır',
    removeImageMessage: '"{name}" imajı sunucudan silinecek. Gerekirse yeniden indirilebilir.',
    removeImageInUse: 'Bu imajı kullanan konteynerler var: {names}. Önce onları kaldırın.',
    removeImageForce: 'Zorla kaldır (birden fazla etiketi varsa hepsini siler)',
    removeImageDone: 'İmaj kaldırıldı.',

    // volumes
    searchVolumes: 'Birim ara',
    colDriver: 'Sürücü',
    colMountpoint: 'Bağlama Noktası',
    colContainers: 'Konteynerler',
    noVolumes: 'Birim yok',
    noVolumesHint: 'Bu sunucuda Docker birimi bulunmuyor.',
    anonymous: 'Anonim',
    removeVolumeTitle: 'Birimi sil',
    removeVolumeMessage: '"{name}" birimi ve içindeki tüm veriler kalıcı olarak silinecek.',
    removeVolumeWarning: 'Bu işlem geri alınamaz. Birimdeki veriler yedeklenmediyse kaybolur.',
    removeVolumeDone: 'Birim silindi.',
    removeVolumeInUse: 'Kullanımda olan birim silinemez',
    pruneVolumes: 'Kullanılmayanları Temizle',
    pruneVolumesTitle: 'Kullanılmayan birimleri sil',
    pruneVolumesIntro: 'Aşağıdaki birimler hiçbir konteyner tarafından kullanılmıyor. Silmek istediklerinizi seçin.',
    pruneVolumesWarning: 'Seçilen birimler ve içlerindeki tüm veriler kalıcı olarak silinir. Bu işlem geri alınamaz.',
    pruneVolumesNone: 'Kullanılmayan birim yok.',
    pruneVolumesSelected: '{n} birim seçildi',
    pruneVolumesSelectAll: 'Tümünü seç',
    pruneVolumesSelectNone: 'Seçimi kaldır',
    pruneVolumesType: 'Onaylamak için {word} yazın',
    pruneVolumesWord: 'sil',
    pruneVolumesConfirm: 'Seçilenleri Sil',
    pruneVolumesDone: '{n} birim silindi.',
    pruneVolumesPartial: '{ok} birim silindi, {fail} birim silinemedi.',
    selectVolume: '{name} birimini seç',

    // networks
    searchNetworks: 'Ağ ara',
    colScope: 'Kapsam',
    colSubnet: 'Alt Ağ / Ağ Geçidi',
    noNetworks: 'Ağ yok',
    noNetworksHint: 'Docker ağı bulunamadı.',
    builtin: 'Yerleşik',
    internal: 'Dahili',
    removeNetworkTitle: 'Ağı kaldır',
    removeNetworkMessage: '"{name}" ağı kaldırılacak.',
    removeNetworkDone: 'Ağ kaldırıldı.',
    removeNetworkBuiltin: 'Yerleşik ağlar kaldırılamaz',
    removeNetworkInUse: 'Konteyner bağlı olan ağ kaldırılamaz',

    // widget
    widgetTitle: 'Docker Konteynerleri',
    widgetAll: 'Tümünü Gör',
    widgetMore: '{n} konteyner daha',
    widgetEmpty: 'Konteyner yok',
    widgetEmptyHint: 'Henüz konteyner oluşturulmamış.',

    // settings
    settingsTitle: 'Docker Motoru',
    settingsSubtitle: 'Sunucudaki Docker kurulumunun bilgileri',
    sVersion: 'Sürüm',
    sApi: 'API sürümü',
    sStorage: 'Depolama sürücüsü',
    sRoot: 'Veri dizini',
    sLogging: 'Log sürücüsü',
    sCgroup: 'Cgroup',
    sOs: 'İşletim sistemi',
    sKernel: 'Kernel',
    sArch: 'Mimari',
    sContainers: 'Konteynerler',
    sContainersValue: '{total} toplam · {running} çalışıyor · {stopped} durmuş',
    sContainersPaused: ' · {paused} duraklatılmış',
    sImages: 'İmajlar',
  },
})

export type StringKey = Parameters<typeof t>[0]
