import { messages } from '@/i18n'

export const t = messages({
  tr: {
    serverStatus: 'Sunucu Durumu',
    online: 'Çevrimiçi',
    connecting: 'Bağlanıyor',
    offline: 'Bağlantı yok',
    uptimeLabel: 'Çalışma süresi: {value}',
    serverTimeLabel: 'Sunucu saati',

    cpu: 'CPU',
    ram: 'RAM',
    disk: 'Disk',
    temperature: 'Sıcaklık',
    loadAverage: 'Yük ortalaması: {value}',
    usedOfTotal: '{used} / {total}',
    memAvailable: '{used} / {total} · {available} kullanılabilir',
    cpuTemp: 'CPU: {value}',
    nvmeTemp: 'NVMe: {value}',
    noSensor: 'Sensör bulunamadı',
    noSensorHint: 'Bu sunucuda okunabilir bir sıcaklık sensörü yok.',
    noRootDisk: 'Kök disk okunamadı',
    measuring: 'Ölçülüyor…',
    trendOf: '{name} eğilimi',
    metricsTitle: 'Sistem ölçümleri',
    streamError: 'Canlı veri akışına bağlanılamadı. Sunucuya erişimi kontrol edip tekrar deneyin.',

    systemInfo: 'Sistem Bilgileri',
    edit: 'Düzenle',
    os: 'İşletim Sistemi',
    kernel: 'Kernel',
    processor: 'İşlemci',
    memory: 'Bellek',
    hostname: 'Sunucu Adı',
    localIp: 'Yerel IP',
    uptime: 'Çalışma Süresi',
    load: 'Yük (Load)',
    time: 'Zaman',
    unknown: 'Bilinmiyor',
    coresThreads: '{cores}C/{threads}T',
    ramShort: '{value} RAM',

    traffic: 'Ağ Trafiği',
    range: 'Zaman aralığı',
    range5m: 'Son 5 Dakika',
    range15m: 'Son 15 Dakika',
    range30m: 'Son 30 Dakika',
    range1h: 'Son 1 Saat',
    download: 'İndirme',
    upload: 'Yükleme',
    trafficChart: 'İndirme ve yükleme hızı grafiği',
    trafficEmpty: 'Veri toplanıyor…',

    storage: 'Depolama',
    seeAll: 'Tümünü Gör',
    noDisks: 'Bağlı disk bulunamadı',
    noDisksHint: 'Sunucuda gösterilecek bağlı bir dosya sistemi yok.',
    diskUsage: '{mount} kullanımı',

    system: 'Sistem',
    statusRunning: 'Çalışıyor',
    statusWarning: 'Uyarı var',
    statusCritical: 'Kritik',
    statusUnknown: 'Bilinmiyor',
    systemSummary: 'Sistem özeti',
    infoError: 'Sistem bilgileri alınamadı.',
    retry: 'Tekrar Dene',

    settingsTitle: 'Sağlık Eşikleri',
    settingsSubtitle: 'Disk doluluğu ve sıcaklık için uyarı ve kritik seviyeleri.',
    diskWarning: 'Disk uyarı eşiği (%)',
    diskCritical: 'Disk kritik eşiği (%)',
    tempWarning: 'Sıcaklık uyarı eşiği (°C)',
    tempCritical: 'Sıcaklık kritik eşiği (°C)',
    hintRange: '{min} ile {max} arasında bir tam sayı.',
    errRange: 'Değer {min} ile {max} arasında bir tam sayı olmalıdır.',
    errOrder: 'Kritik eşik, uyarı eşiğinden büyük olmalıdır.',
    save: 'Kaydet',
    saved: 'Sağlık eşikleri kaydedildi.',
    adminOnly: 'Bu ayarları yalnızca yöneticiler değiştirebilir.',
  },
})
